export {default as AdminPage} from './Admin'
export {default as CategoryPage} from './Category'
export {default as ProductPage} from './Product'
export {default as Edit} from './EditProduct'
export {default as Orders} from './Orders'